cluster.name: "es-docker-cluster"
network.host: 0.0.0.0

# Minimum master nodes
discovery.zen.minimum_master_nodes: 1

# Security settings
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true

# Memory settings
bootstrap.memory_lock: true

# JVM settings
bootstrap.system_call_filter: false

# Cross-origin resource sharing
http.cors.enabled: true
http.cors.allow-origin: "*"

# Index lifecycle management
xpack.ilm.enabled: true

# Snapshot and restore
path.repo: ["/usr/share/elasticsearch/snapshots"]
