server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.username: elastic
elasticsearch.password: ${ELASTIC_PASSWORD}

# Security settings
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long"
xpack.reporting.encryptionKey: "something_at_least_32_characters_long"

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true

# Default index pattern
kibana.defaultAppId: "home"

# Logging
logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: pattern
  root:
    appenders: [file]
    level: info
